import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
// import { ErrorWrapper } from './error-wrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: {
    default: 'Practice Application',
    template: '%s | Practice Application'
  },
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-between p-4 bg-gray-500 shadow-md">
          <h1 className="text-3xl font-bold">My Application</h1>
        </header>
        {/* <ErrorWrapper> */}
        {children}
        {/* </ErrorWrapper> */}
        <footer className="mt-8">
          <div className="text-center p-4 bg-gray-500 border-t">
            © {new Date().getFullYear()} My Application
          </div>
        </footer>
      </body>
    </html>
  );
}
